print("the area and perimeter of a triangle")
l=int(input("enter the length of trianle"))
b=int(input("enter the breadth of triangle"))
print("area of the triangle is:",l*b)
print("perimeter of the triangle is:",2*(l+b))
